language: node_js
# nodejs版本
node_js: 
     - "v11.14.0"  # 对应的版本
# Travis-CI Caching
cache:
  directories:
    - node_modules
# S: Build Lifecycle
install:
  - npm install
before_script:
# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
branches:
  only:
    - master