language: node_js # 构建所需的语言环境
node_js:
  - "v11.14.0"  # 对应的版本
branches:
  only:
  - master    # 构建的分支
cache:
  directories:
  - node_modules # 依赖缓存的目录
install:
 - npm install -g gitbook-cli # 安装编译工具
script:
- yarn install
- yarn test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  target-branch: gh-pages
  verbose: true
  on:
    branch: master